### ISSUE TITLE
Unable crunch files while building project v7 and appcompat

### ISSUE THREAD

**Issue by ghost** [material-foundation/material-remixer-android#43]
To project owner: could You to add note about above problem? It occurs when absolute path is too long. Happens on Windows7 x64 Android Studio 2.2.2

**Comment by miguelandres** [comment]
Can you detail the error? 

I'm not sure what you mean. Please copy the gradle log (verbose) to see what's going on.

Also it may take me a while to look into this because I don't have a Windows machine readily available (I may be able to take a look in Windows 10 later, but I think it'll be hard to find a windows 7 machine for me, so more details may help understand).

**Comment by miguelandres** [comment]
@mmokrzycki can you please give me a detailed log of what the error is?

**Comment by ghost** [comment]
The problem was during importing project to PC when the project was somewhere on hardrive and the absolute path to it was relatively very long i.e. 
C:\xxxxxxxxxxxxxxxxxxxx\yyyyyyyyyyyyyyyyyyyyyyyy\zzzzzzzzzzzzzzzz\ThisProjectFolder.... 
I had to rename project to shorter names and then project builded with success.

**Comment by miguelandres** [comment]
But what was the error you got? what was it that didn't work @mmokrzycki?

Do you have a log or screenshot?

From what little I can gather this sounds more like you're encountering
some filesystem limitation (specifically
https://msdn.microsoft.com/en-us/library/aa365247.aspx#maxpath) which would
be out of scope for the Remixer project. You may find those limitations
with any other application or project (and no other project makes such a
note).

Of course, java projects are more prone to run against such limits since
the path includes the package name verbatim, which tend to be long by java
conventions.

Either way I need more information to decide what to do.

**Comment by miguelandres** [comment]
I'm closing this bug since it seems to be the case that this is the 260 character file path limit. We're not close to reaching that so it's a very setup-specific issue that I do not think is in the scope of the project.
